### ISSUE TITLE
Integration Testing Utility

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leapdao-bounties#25]
# Bounty 42:

## Requirements
check https://hackmd.io/s/r100DohCQ#TODO

## Deliverables
- a repo that holds scripts to launch a local testnet
-  example tests that can be run against the testnet
- 

## Gain for the project
- Ability to do integration tests.
- automation of manual testing.

----
gardener: @eezcjkr | 10%
worker: @eezcjkr  | 80%
reviewer: @troggy  | 10%

**Comment by troggy** [comment]
the whole thing is done here https://github.com/leapdao/leapdao-integ-tests
